# Generated by Django 6.0.4 on 2026-05-07 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram Ads"),
                            ("vk", "VK Ads"),
                            ("yandex", "Yandex Direct"),
                            ("google", "Google Ads"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активна"),
                            ("paused", "На паузе"),
                            ("completed", "Завершена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "budget",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Бюджет",
                    ),
                ),
                (
                    "spent",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Потрачено",
                    ),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Показы",
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Клики",
                    ),
                ),
                (
                    "leads",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Лиды",
                    ),
                ),
                (
                    "conversions",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Конверсии",
                    ),
                ),
                (
                    "revenue",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Выручка",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата запуска")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Рекламная кампания",
                "verbose_name_plural": "Рекламные кампании",
                "ordering": ["-created_at"],
            },
        ),
    ]
