# Generated by Django 6.0.4 on 2026-05-05 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата оформления"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Общая сумма",
            ),
        ),
    ]
