# Generated by Django 6.0.4 on 2026-05-05 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
    ]
