# Generated by Django 6.0.4 on 2026-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/photos/",
                verbose_name="Фотография",
            ),
        ),
    ]
